/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beta;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;
//import net.sf.jasperreports.engine.JRException;
//import net.sf.jasperreports.engine.JasperCompileManager;
//import net.sf.jasperreports.engine.JasperExportManager;
//import net.sf.jasperreports.engine.JasperFillManager;
//import net.sf.jasperreports.engine.JasperPrint;
//import net.sf.jasperreports.engine.JasperReport;
//import net.sf.jasperreports.engine.design.JasperDesign;
//import net.sf.jasperreports.engine.xml.JRXmlLoader;

/**
 *
 * @author JoshBatey
 */
public final class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    Connection kon;
    PreparedStatement pst;
    ResultSet rs;
    public Sales() {
        initComponents();
        kon =  Konexio.konexio();
        this.tableBill();
        tableContain();
        new Product().table(tbl_Bills);
      //  new Product().table(tbl_cont);
        combo();
        comboB();
        BillAdd.setVisible(false);
        Home.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void rep() throws FileNotFoundException{
//        JasperPrint jp = null;
        String  nom ="";
        String requete ="";
        try{
            Map par = new HashMap();
            HashMap myParameters = new HashMap();
            myParameters.put("market", "HopeIN Supermarket");
            myParameters.put("controller", "Cashier Name");
            String red ="";
            requete = "SELECT `Bill_ID` as field1,`Bill_DATE` as field2,"
                    + "`Receipt_ID` as field3,`bar_code` as field4,"
                    + "`designation` as field5,`price` as field6,"
                    + "`Quantity` as field7,`name` as field9,`Amount` as field8 FROM `billreceipt` ";
            myParameters.put("sql", requete);
            String src = "Receipt.jrxml";
            InputStream inputStream = new FileInputStream (src);
//            JasperDesign jDesign = JRXmlLoader.load(inputStream);
//            JasperReport jReport = JasperCompileManager.compileReport(jDesign);
//            JasperPrint jPrint = JasperFillManager.fillReport(jReport, myParameters,kon);
//            JasperExportManager.exportReportToPdfFile(jPrint,"Facture.pdf");
        }
        catch(FileNotFoundException e){
            throw new RuntimeException("It's not Possible to generate the PDF report", e);
            
        }
    }
    
    private void combo(){
        try
        {
            if(!kon.isClosed()){
                String sql ="Select * from clients";
                    pst=kon.prepareStatement(sql);
                    rs=pst.executeQuery();
                while(rs.next())
                {
                    String name=rs.getString("id");
                    //SeachClient.addItem(name);
                }
            }
            else
                kon.close();
        }
        catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    public void tableBill()
    {
        try
        {
            if(!kon.isClosed()){
                String sql ="SELECT * FROM `bills`";
                pst=kon.prepareStatement(sql);
                rs=pst.executeQuery();
                tbl_Bills.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else
                kon.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
     public void tableContain()
    {
        try
        {
            if(!kon.isClosed()){
                String sql ="SELECT * FROM `contain`";
                pst=kon.prepareStatement(sql);
                rs=pst.executeQuery();
               // tbl_cont.setModel(DbUtils.resultSetToTableModel(rs));
            }
            else
                kon.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void comboB()
    {
        try
        {
            if(!kon.isClosed()){
                String sql ="SELECT distinct bill_date FROM `bills`";
                pst=kon.prepareStatement(sql);
                rs=pst.executeQuery();
                while(rs.next()){
                    String name=rs.getString("bill_date");
                   // cb_Bill_Date.addItem(name);
                }
            }
            else
                kon.close();
        }
        catch(SQLException ex)
        {
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BillAdd = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txt_ID_Bill = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        date_Bill = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Bills = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_ID_Client = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txt_NAME_Client = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_PHONE_Client = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        Home = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        txt_ID_Product = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txt_Des_Product = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_PRICE_Product = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txt_NATURE_Product = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_Stock_Qty = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        txt_Sales_Qty = new javax.swing.JTextField();
        pane_Total = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_BarCode_Search = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 64, 64));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/home.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/pro.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/out.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Home");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Add Bill");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Log Out");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        BillAdd.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bill Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 64, 64))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setRequestFocusEnabled(false);

        jLabel3.setBackground(new java.awt.Color(0, 64, 64));
        jLabel3.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 64, 64));
        jLabel3.setText("Bill ID");

        txt_ID_Bill.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txt_ID_Bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ID_BillActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 64, 64));
        jLabel7.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 64, 64));
        jLabel7.setText("Date");

        date_Bill.setDateFormatString(" yyyy-MMM- dd");
        date_Bill.setMinimumSize(new java.awt.Dimension(6, 29));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(txt_ID_Bill)
                    .addComponent(jLabel7)
                    .addComponent(date_Bill, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ID_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(date_Bill, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tbl_Bills.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill_ID", "Bill_DATE", "Client_ID"
            }
        ));
        tbl_Bills.setFocusable(false);
        tbl_Bills.setGridColor(new java.awt.Color(0, 64, 64));
        tbl_Bills.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_Bills.setRowHeight(30);
        tbl_Bills.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbl_Bills.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tbl_Bills.getTableHeader().setReorderingAllowed(false);
        tbl_Bills.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_BillsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Bills);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 12), new java.awt.Color(0, 64, 64))); // NOI18N
        jPanel3.setOpaque(false);

        jLabel9.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 64, 64));
        jLabel9.setText("Client ID");

        txt_ID_Client.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txt_ID_Client.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ID_ClientKeyReleased(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 64, 64));
        jLabel13.setText("Name");

        txt_NAME_Client.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 64, 64));
        jLabel14.setText("Phone");

        txt_PHONE_Client.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9)
            .addComponent(txt_ID_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel13)
            .addComponent(txt_NAME_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jLabel14)
            .addComponent(txt_PHONE_Client, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ID_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NAME_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PHONE_Client, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jLabel16.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 64, 64));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/add.png"))); // NOI18N
        jLabel16.setText("Add Clients? ");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(0, 64, 64));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/insertwhite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BillAddLayout = new javax.swing.GroupLayout(BillAdd);
        BillAdd.setLayout(BillAddLayout);
        BillAddLayout.setHorizontalGroup(
            BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillAddLayout.createSequentialGroup()
                .addGroup(BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BillAddLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(BillAddLayout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97)
                                .addComponent(jLabel16)))
                        .addGap(96, 96, 96)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BillAddLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        BillAddLayout.setVerticalGroup(
            BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BillAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(BillAddLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(BillAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BillAddLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(BillAddLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel16)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jPanel1.add(BillAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 730, 540));

        Home.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 64, 64))); // NOI18N
        jPanel4.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 64, 64));
        jLabel18.setText("Product ID");

        txt_ID_Product.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 64, 64));
        jLabel19.setText("Designation");

        txt_Des_Product.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 64, 64));
        jLabel20.setText("Price");

        txt_PRICE_Product.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel21.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 64, 64));
        jLabel21.setText("Nature");

        txt_NATURE_Product.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        jLabel22.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 64, 64));
        jLabel22.setText("Stock Quantity");

        txt_Stock_Qty.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel22)
                        .addComponent(txt_Stock_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18)
                        .addComponent(txt_ID_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(txt_Des_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)
                        .addComponent(txt_PRICE_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21)
                        .addComponent(txt_NATURE_Product, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_ID_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_Des_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_PRICE_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NATURE_Product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addGap(10, 10, 10)
                .addComponent(txt_Stock_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Century Gothic", 0, 12), new java.awt.Color(0, 64, 64))); // NOI18N
        jPanel5.setOpaque(false);

        jLabel23.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 64, 64));
        jLabel23.setText("Quantity");

        txt_Sales_Qty.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txt_Sales_Qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Sales_QtyKeyReleased(evt);
            }
        });

        pane_Total.setFont(new java.awt.Font("Yu Gothic", 1, 14)); // NOI18N
        pane_Total.setForeground(new java.awt.Color(0, 64, 64));
        pane_Total.setText("0.00 Frw");

        jPanel7.setBackground(new java.awt.Color(0, 64, 64));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
        });

        jLabel24.setBackground(new java.awt.Color(0, 64, 64));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/insertwhite.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 12)); // NOI18N
        jLabel10.setText("Print");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel23))
                    .addComponent(txt_Sales_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(pane_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(28, 28, 28))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel23)
                .addGap(10, 10, 10)
                .addComponent(txt_Sales_Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pane_Total)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(22, 22, 22))))
        );

        jLabel11.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 64, 64));
        jLabel11.setText("Bar Code Scan");

        txt_BarCode_Search.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        txt_BarCode_Search.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 64, 64)));
        txt_BarCode_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_BarCode_SearchActionPerformed(evt);
            }
        });
        txt_BarCode_Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_BarCode_SearchKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(HomeLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(36, 36, 36)
                        .addComponent(txt_BarCode_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_BarCode_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 730, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 868, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(876, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_BarCode_SearchKeyReleased(KeyEvent evt) {//GEN-FIRST:event_txt_BarCode_SearchKeyReleased
        if(txt_BarCode_Search.getText().equals(""))
        {
            txt_ID_Product.setText("");
            txt_Des_Product.setText("");
            txt_PRICE_Product.setText("");
            txt_NATURE_Product.setText("");
            txt_Stock_Qty.setText("");
        }
        else if(evt.getKeyCode() == KeyEvent.VK_ENTER)
        {
            try
            {
                if(!kon.isClosed()){
                    String query ="SELECT * FROM `products` WHERE `bar_code`='"+txt_BarCode_Search.getText()+"'";
                    pst = kon.prepareStatement(query);
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                     String add=rs.getString("id");
                     txt_ID_Product.setText(add);
                     String add1=rs.getString("designation");
                     txt_Des_Product.setText(add1);
                     String add2=rs.getString("price");
                     txt_PRICE_Product.setText(add2);
                     String add3=rs.getString("nature");
                     txt_NATURE_Product.setText(add3);
                     String add4=rs.getString("stock_qty");
                     txt_Stock_Qty.setText(add4);
                    } 
                }
                else
                    kon.close();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Error:: \n"+e);
            }
        }
//        else
//        {
//            JOptionPane.showMessageDialog(null,"Product Not Found");
//        }
    }//GEN-LAST:event_txt_BarCode_SearchKeyReleased

    private void tbl_BillsMouseClicked(MouseEvent evt) {//GEN-FIRST:event_tbl_BillsMouseClicked
        try {
            TableModel model=tbl_Bills.getModel();
            txt_ID_Bill.setText(model.getValueAt(tbl_Bills.getSelectedRow(),0).toString());
            date_Bill.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(tbl_Bills.getSelectedRow(), 1)));
            txt_ID_Client.setText(model.getValueAt(tbl_Bills.getSelectedRow(),2).toString());
        } catch (ParseException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_BillsMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Home.setVisible(true);
        BillAdd.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Home.setVisible(false);
        BillAdd.setVisible(true);
       
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.setVisible(false);
        new ViewLogin().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txt_ID_BillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ID_BillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ID_BillActionPerformed

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        try
        {
            if(!kon.isClosed()){
                String q ="INSERT INTO `bills`(`bill_date`, `id_client`) VALUES (?,?)";
                pst = kon.prepareStatement(q);
                pst.setString(1,((JTextField)date_Bill.getDateEditor().getUiComponent()).getText());
                pst.setString(2,txt_ID_Client.getText());
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Succefully Saved");
                tableBill();
            }
            else
            kon.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Not Saved"+ e);
        }
    }//GEN-LAST:event_jPanel6MouseClicked

    private void txt_ID_ClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ID_ClientKeyReleased
        if(txt_ID_Client.getText().equals(""))
        {
            txt_NAME_Client.setText("");
            txt_PHONE_Client.setText("");
        }
        else
        {
            try
            {
                if(!kon.isClosed()){
                    String query ="SELECT * FROM `clients` WHERE `id`=?";
                    pst = kon.prepareStatement(query);
                    pst.setString(1,txt_ID_Client.getText());
                    rs=pst.executeQuery();
                    if(rs.next())
                    {
                        String add=rs.getString("name");
                        txt_NAME_Client.setText(add);
                        String add1=rs.getString("phone");
                        txt_PHONE_Client.setText(add1);
                    }
                }
                else
                kon.close();
            }
            catch(SQLException e)
            {
                JOptionPane.showMessageDialog(null,"Error:: \n"+e);
            }
        }
    }//GEN-LAST:event_txt_ID_ClientKeyReleased

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        this.setVisible(false);
        new Clients().setVisible(true);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void txt_Sales_QtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Sales_QtyKeyReleased
        int a= Integer.parseInt(txt_PRICE_Product.getText()) * Integer.parseInt(txt_Sales_Qty.getText());
        pane_Total.setText(a + " Frw");
    }//GEN-LAST:event_txt_Sales_QtyKeyReleased

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        try
        {
            if(!kon.isClosed()){
                String q ="INSERT INTO `contain`(`id_bill`, `id_product`, `bill_qty`) VALUES (?,?,?)";
                pst = kon.prepareStatement(q);
                int idB = Integer.parseInt(txt_ID_Bill.getText());
                int idP = Integer.parseInt(txt_ID_Product.getText());
                int qty = Integer.parseInt(txt_Sales_Qty.getText());
                pst.setInt(1,idB);
                pst.setInt(2,idP);
                pst.setInt(3,qty);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null,"Succefully Saved");
                tableContain();
                
            }
            else
            kon.close();
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Not Saved"+ e);
        }
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        try {
            rep();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel10MouseClicked

    private void txt_BarCode_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_BarCode_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_BarCode_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Sales().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BillAdd;
    private javax.swing.JPanel Home;
    private com.toedter.calendar.JDateChooser date_Bill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel pane_Total;
    private javax.swing.JTable tbl_Bills;
    private javax.swing.JTextField txt_BarCode_Search;
    private javax.swing.JTextField txt_Des_Product;
    private javax.swing.JTextField txt_ID_Bill;
    private javax.swing.JTextField txt_ID_Client;
    private javax.swing.JTextField txt_ID_Product;
    private javax.swing.JTextField txt_NAME_Client;
    private javax.swing.JTextField txt_NATURE_Product;
    private javax.swing.JTextField txt_PHONE_Client;
    private javax.swing.JTextField txt_PRICE_Product;
    private javax.swing.JTextField txt_Sales_Qty;
    private javax.swing.JTextField txt_Stock_Qty;
    // End of variables declaration//GEN-END:variables
}
