/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beta;

/**
 *
 * @author Batey
 */
public class Try extends javax.swing.JFrame {

    /**
     * Creates new form Try
     */
    public Try() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_Product = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtSearchProduct = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        user = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_User = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txtSearchUser = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        client = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSearchClient = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_client = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        product.setBackground(new java.awt.Color(255, 255, 255));

        tbl_Product.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        tbl_Product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_Product.setFocusable(false);
        tbl_Product.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_Product.setRowHeight(25);
        tbl_Product.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbl_Product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_ProductMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_Product);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 64, 64));
        jLabel9.setText("Search Product");

        txtSearchProduct.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSearchProduct.setForeground(new java.awt.Color(0, 64, 64));
        txtSearchProduct.setText("Product");
        txtSearchProduct.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 51)));
        txtSearchProduct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchProductKeyReleased(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 64, 64));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/add.png"))); // NOI18N
        jLabel12.setText("New Product");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout productLayout = new javax.swing.GroupLayout(product);
        product.setLayout(productLayout);
        productLayout.setHorizontalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                .addContainerGap(231, Short.MAX_VALUE)
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(productLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel12)))
                .addContainerGap())
        );
        productLayout.setVerticalGroup(
            productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productLayout.createSequentialGroup()
                .addGroup(productLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel9))
                    .addGroup(productLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, productLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)))
                .addGap(87, 87, 87)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(product, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        user.setBackground(new java.awt.Color(255, 255, 255));

        tbl_User.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        tbl_User.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_User.setFocusable(false);
        tbl_User.setGridColor(new java.awt.Color(0, 64, 64));
        tbl_User.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_User.setRowHeight(25);
        tbl_User.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbl_User.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UserMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_User);

        jLabel17.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 64, 64));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/add.png"))); // NOI18N
        jLabel17.setText("New User");
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        txtSearchUser.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSearchUser.setForeground(new java.awt.Color(0, 64, 64));
        txtSearchUser.setText("User");
        txtSearchUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 51)));
        txtSearchUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchUserKeyReleased(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 64, 64));
        jLabel18.setText("Search User");

        javax.swing.GroupLayout userLayout = new javax.swing.GroupLayout(user);
        user.setLayout(userLayout);
        userLayout.setHorizontalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 818, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel17)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18)))
                .addGap(1329, 1329, 1329))
        );
        userLayout.setVerticalGroup(
            userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userLayout.createSequentialGroup()
                .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 860, -1));

        client.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 64, 64));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/beta/images/add.png"))); // NOI18N
        jLabel14.setText("New Client");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 64, 64));
        jLabel13.setText("Search Client");

        txtSearchClient.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtSearchClient.setForeground(new java.awt.Color(0, 64, 64));
        txtSearchClient.setText("Client");
        txtSearchClient.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 51, 51)));
        txtSearchClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchClientKeyReleased(evt);
            }
        });

        tbl_client.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        tbl_client.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbl_client.setFocusable(false);
        tbl_client.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tbl_client.setRowHeight(25);
        tbl_client.setSelectionBackground(new java.awt.Color(255, 102, 102));
        tbl_client.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_clientMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_client);

        javax.swing.GroupLayout clientLayout = new javax.swing.GroupLayout(client);
        client.setLayout(clientLayout);
        clientLayout.setHorizontalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addGap(41, 41, 41)
                .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1223, 1223, 1223))
        );
        clientLayout.setVerticalGroup(
            clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(clientLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtSearchClient, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        getContentPane().add(client, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, 620, 290));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_ProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_ProductMouseClicked
        //        try {
            //            TableModel model=tbl_Product.getModel();
            //            txt_Prod_ID.set;Text(model.getValueAt(tbl_Product.getSelectedRow(),0).toString());
            //            txt_Prod_Des.setText(model.getValueAt(tbl_Product.getSelectedRow(),1).toString());
            //            txt_Prod_Price.setText(model.getValueAt(tbl_Product.getSelectedRow(),2).toString());
            //            cb_Prod_Nature.setSelectedItem(model.getValueAt(tbl_Product.getSelectedRow(),3).toString());
            //            cb_Prod_category.setSelectedItem(model.getValueAt(tbl_Product.getSelectedRow(),4).toString());
            //            txt_Prod_BarCode.setText(model.getValueAt(tbl_Product.getSelectedRow(),5).toString());
            //            txt_Prod_ExpDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(tbl_Product.getSelectedRow(), 6)));
            //            txt_Prod_Description.setText(model.getValueAt(tbl_Product.getSelectedRow(),7).toString());
            //            txt_Prod_qtyINStock.setText(model.getValueAt(tbl_Product.getSelectedRow(),8).toString());
            //            txt_Prod_StockDate.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(tbl_Product.getSelectedRow(), 9)));
            //        } catch (ParseException ex) {
            //            Logger.getLogger(Product.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_tbl_ProductMouseClicked

    private void txtSearchProductKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchProductKeyReleased
        if (txtSearchProduct.getText().equals("")) {
            tablePro();
        } else {
            try {
                if (!kon.isClosed()) {
                    String query = "SELECT bar_code,designation,price,stock_qty,exp_date FROM `products` WHERE `designation` like '%" + txtSearchProduct.getText() + "%'";
                    pst = kon.prepareStatement(query);
                    // pst.setString(1,txt_search.getText());
                    rs = pst.executeQuery();
                    tbl_Product.setModel(DbUtils.resultSetToTableModel(rs));
                } else {
                    kon.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error:: \n" + e);
            }
        }
    }//GEN-LAST:event_txtSearchProductKeyReleased

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        this.setVisible(false);
        new ProductA().setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void tbl_UserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UserMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_UserMouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void txtSearchUserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchUserKeyReleased
        if (txtSearchUser.getText().equals("")) {
            tableUsers();
        } else {
            try {
                if (!kon.isClosed()) {
                    String query = "SELECT * from users WHERE `usernames` like '%" + txtSearchUser.getText() + "%'";
                    pst = kon.prepareStatement(query);
                    // pst.setString(1,txt_search.getText());
                    rs = pst.executeQuery();
                    tbl_User.setModel(DbUtils.resultSetToTableModel(rs));
                } else {
                    kon.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error:: \n" + e);
            }
        }
    }//GEN-LAST:event_txtSearchUserKeyReleased

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);
        new ClientsA().setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void txtSearchClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchClientKeyReleased
        try {
            if (!kon.isClosed()) {
                String query = "SELECT * FROM `clients` WHERE `name` like '%" + txtSearchClient.getText() + "%'";
                pst = kon.prepareStatement(query);
                //pst.setString(1,txt_search.getText());
                rs = pst.executeQuery();
                tbl_client.setModel(DbUtils.resultSetToTableModel(rs));
                //table();
            } else {
                kon.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error:: \n" + e);
        }
    }//GEN-LAST:event_txtSearchClientKeyReleased

    private void tbl_clientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_clientMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_clientMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Try.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Try.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Try.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Try.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Try().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel client;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel product;
    private javax.swing.JTable tbl_Product;
    private javax.swing.JTable tbl_User;
    private javax.swing.JTable tbl_client;
    private javax.swing.JTextField txtSearchClient;
    private javax.swing.JTextField txtSearchProduct;
    private javax.swing.JTextField txtSearchUser;
    private javax.swing.JPanel user;
    // End of variables declaration//GEN-END:variables
}
